title: Self-Hosted LLMs für Datensouveränität
description: Von der ersten Installation über Fine-tuning bis zur vollständigen Datensouveränität
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
repository: hanasobi/self-hosted-llms-tutorial
defaults:
  - scope:
      path: "posts"
    values:
      layout: default
      title: Self-Hosted LLMs für Datensouveränität